openapi: 3.0.1
info:
  title: Anstalld
  version: 0.1.0
servers:
- url: "{server}:{port}/anstalld"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /hamtaAnstalld:
    get:
      operationId: getHamtaanstalld
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /skapaAnstalld:
    post:
      operationId: postSkapaanstalld
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalld'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /hamtaAllaAnstalldaByIdAsc:
    get:
      operationId: getHamtaallaanstalldabyidasc
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /hamtaAllaAnstalldaByLastNameAsc:
    get:
      operationId: getHamtaallaanstalldabylastnameasc
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /uppdateraAnstalld:
    put:
      operationId: putUppdateraanstalld
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalld'
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /tabortAnstalld:
    delete:
      operationId: deleteTabortanstalld
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
    anstalld:
      required:
      - comment
      - created
      - firstNamn
      - lastName
      - updated
      - workTitle
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstNamn:
          type: string
        lastName:
          type: string
        workTitle:
          type: string
        created:
          type: string
        updated:
          type: string
        comment:
          type: string
      additionalProperties: false
