openapi: 3.0.1
info:
  title: Anstalld API
  version: 1.0.0
servers:
  - url: https://6de04eb5-ff57-4d64-b80e-6284e10f8dc5-dev.e1-eu-north-azure.choreoapis.dev/full-stack-test-project/rest-api-mot-neondb/v1.0
paths:
  /hamtaAnstalld:
    get:
      summary: Hämta en anställd via ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: En eller flera anställda
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
        '404':
          description: Ingen anställd hittades
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /skapaAnstalld:
    post:
      summary: Skapa en ny anställd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalld'
            example:
              firstNamn: "Förnamn"
              lastName: "Efternamn"
              workTitle: "Title"
              created: "YYYY-MM-DD"
              updated: "YYYY-MM-DD"
              comment: "Kommentar (optional)"
      responses:
        '200':
          description: Skapningsresultat
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /allaAnstallda:
    get:
      summary: Hämta alla anställda
      responses:
        '200':
          description: Lista av anställda
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
        '500':
          description: Fel vid hämtning
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /updateAnstalld:
    get:
      summary: Uppdatera anställd (demo/fördefinierad text)
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Svarstext
          content:
            text/plain:
              schema:
                type: string

  /tabortAnstalld:
    delete:
      summary: Ta bort en anställd via ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Resultatmeddelande
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Anställd hittades inte
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    anstalld:
      type: object
      properties:
        id:
          type: integer
        firstNamn:
          type: string
        lastName:
          type: string
        workTitle:
          type: string
        created:
          type: string
        updated:
          type: string
        comment:
          type: string
