openapi: 3.1.0
info:
  title: Anstalld API
  version: 1.0.0
servers:
  - url: https://6de04eb5-ff57-4d64-b80e-6284e10f8dc5-dev.e1-eu-north-azure.choreoapis.dev/full-stack-test-project/rest-api-mot-neondb/v1.0
paths:
  /hamtaAnstalld:
    get:
      summary: Hämta en anställd
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: En anställd
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/anstalld'
        '404':
          description: Ingen anställd hittades
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
  /createAnstalld:
    get:
      summary: Skapa anställd (demo)
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Skapad
          content:
            text/plain:
              schema:
                type: string
  /readAnstalld:
    get:
      summary: Läs anställda (demo)
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /allaAnstallda:
    get:
      summary: Hämta alla anställda
      responses:
        '200':
          description: Lista av anställda
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
        '500':
          description: Fel vid hämtning
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
  /updateAnstalld:
    get:
      summary: Uppdatera anställd (demo)
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Uppdaterad
          content:
            text/plain:
              schema:
                type: string
  /deleteAnstalld:
    get:
      summary: Ta bort anställd (demo)
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Borttagen
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    anstalld:
      type: object
      properties:
        id:
          type: integer
        firstNamn:
          type: string
        lastName:
          type: string
        workTitle:
          type: string
        created:
          type: string
        updated:
          type: string
        comment:
          type: string
