openapi: 3.0.1
info:
  title: Anstalld API
  version: 1.0.0
servers:
  - url: https://6de04eb5-ff57-4d64-b80e-6284e10f8dc5-dev.e1-eu-north-azure.choreoapis.dev/full-stack-test-project/rest-api-mot-neondb/v1.0
paths:
  /hamtaAnstalld:
    get:
      summary: Hämta en anställd via ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          example: 1
      responses:
        '200':
          description: En eller flera anställda
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
        '404':
          description: Ingen anställd hittades
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anställd hittades inte"

  /skapaAnstalld:
    post:
      summary: Skapa en ny anställd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalldCreate'
            example:
              firstNamn: "Anna"
              lastName: "Andersson"
              workTitle: "Systemutvecklare"
              created: "2025-07-04"
              updated: "2025-07-04"
              comment: "Ny på jobbet"
      responses:
        '200':
          description: Resultat av skapandet
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anställd skapades!"
                  id:
                    type: integer
                    example: 123

  /hamtaAllaAnstallda:
    get:
      summary: Hämta alla anställda
      responses:
        '200':
          description: Lista av anställda
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
        '500':
          description: Fel vid hämtning
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Kunde inte hämta anställda"

  /uppdateraAnstalld:
    put:
      summary: Uppdatera en anställd via ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalldCreate'
            example:
              firstNamn: "Anna"
              lastName: "Andersson"
              workTitle: "Systemutvecklare"
              created: "2025-07-04"
              updated: "2025-07-05"
              comment: "Uppdaterad kommentar"
      responses:
        '200':
          description: Resultat av uppdateringen
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anställd uppdaterades!"
                  id:
                    type: integer
                    example: 1
        '400':
          description: Fel vid uppdatering
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Kunde inte uppdatera anställd!"

  /tabortAnstalld:
    delete:
      summary: Ta bort en anställd via ID
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          example: 1
      responses:
        '200':
          description: Resultat av borttagning
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anställd med id: 1 borttagen!"
        '404':
          description: Anställd hittades inte
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anställd med id: 1 saknas!"

components:
  schemas:
    anstalld:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstNamn:
          type: string
          example: "Anna"
        lastName:
          type: string
          example: "Andersson"
        workTitle:
          type: string
          example: "Systemutvecklare"
        created:
          type: string
          format: date
          example: "2025-07-04"
        updated:
          type: string
          format: date
          example: "2025-07-04"
        comment:
          type: string
          example: "Ny på jobbet"

    # Schema för POST och PUT - utan id (autogenererat i DB)
    anstalldCreate:
      type: object
      required:
        - firstNamn
        - lastName
        - workTitle
        - created
        - updated
        - comment
      properties:
        firstNamn:
          type: string
          example: "Anna"
        lastName:
          type: string
          example: "Andersson"
        workTitle:
          type: string
          example: "Systemutvecklare"
        created:
          type: string
          format: date
          example: "2025-07-04"
        updated:
          type: string
          format: date
          example: "2025-07-04"
        comment:
          type: string
          example: "Ny på jobbet"
