openapi: 3.1.0
info:
  title: Anstalld API
  version: 1.0.0
  description: API för att hantera anställda
servers:
  - url: http://localhost:9090/anstalld
paths:
  /:
    get:
      summary: Hämta alla anställda
      responses:
        '200':
          description: Lyckad hämtning
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/anstalld'
    put:
      summary: Uppdatera en anställd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalld'
      responses:
        '200':
          description: Lyckad uppdatering
          content:
            application/json:
              schema:
                type: integer
    post:
      summary: Lägg till en anställd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/anstalld'
      responses:
        '200':
          description: Lyckad skapelse
          content:
            application/json:
              schema:
                type: integer
  /{id}:
    get:
      summary: Hämta en anställd via id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lyckad hämtning
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/anstalld'
    delete:
      summary: Ta bort en anställd via id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lyckad borttagning
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    anstalld:
      type: object
      properties:
        id:
          type: integer
        firstNamn:
          type: string
        lastName:
          type: string
        workTitle:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        comment:
          type: string
