openapi: 3.1.0
info:
  title: REST API mot Neon DB
  version: 1.0.0
servers:
  - url: http://localhost:8080/rest-api-mot-neon-db
paths:
  /rest-api-mot-neon-db/sayHelloEasy:
    get:
      summary: Returns a simple hello message
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /rest-api-mot-neon-db/sayHelloWithName:
    get:
      summary: Returns a hello message with a name
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /rest-api-mot-neon-db/sayHelloWithNameAndAge:
    get:
      summary: Returns a hello message with a name and age
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
        - in: query
          name: age
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
